services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html/public
    environment:
      - APP_ENV=development
    container_name: freecad-website
    